apiVersion: v1 
kind: ConfigMap 
metadata: 
 name: pod-config 
spec: 
 containers: 
 - name: nginx 
   image: nginx 
   env: 
   - name: course 
     valueFrom: 
      ConfigMapRef: 
       name: nginx-config 
       key: course 
   - name: duration 
     valueFrom:
      ConfigMapRef:
       name: nginx-config 
       key: duration  

